import { calculateDay, calculateMonth, emptyEntry, localDate, numberFields } from './calculations.js'
import { moveMonth } from './monthNavigation.js'

const yen=n=>`¥${Math.round(n).toLocaleString('ja-JP')}`, pct=n=>`${n.toFixed(1)}%`, currentMonth=localDate().slice(0,7)
const seed=[
  [1,48500,12800,8960,8200,6150,4300,3440,15200,2100],[2,42000,9500,6650,6800,5100,3600,2880,13800,1600],[3,56700,15200,10640,9200,6900,5100,4080,18100,2400],[4,39800,8800,6160,7100,5325,2900,2320,12100,1200],[5,61200,18400,12880,10500,7875,6200,4960,21200,3200],[6,58400,16600,11620,9800,7350,5400,4320,19500,2800],[7,36200,7900,5530,5900,4425,2500,2000,11000,900]
].map(v=>Object.fromEntries(['date',...numberFields].map((k,i)=>[k,i? v[i]:`${currentMonth}-${String(v[0]).padStart(2,'0')}`])))
let entries=JSON.parse(localStorage.getItem('moka-entries-v1')||'null')||seed, month=currentMonth
const app=document.querySelector('#app')
const icon=(name)=>`<span class="ui-icon" aria-hidden="true">${({coffee:'☕',chart:'▥',calendar:'▦',store:'⌂',plus:'＋',wallet:'¥',edit:'✎',close:'×'}[name])}</span>`
const stat=(label,value,sub,tone='')=>`<article class="stat ${tone}"><div class="stat-label">${label}</div><strong>${value}</strong><small>${sub}</small></article>`

function chart(data){const vals=data.map(e=>calculateDay(e).sales),max=Math.max(...vals,1),x=i=>data.length===1?50:i/(data.length-1)*100, pts=vals.map((v,i)=>`${x(i)},${92-v/max*78}`).join(' ');return `<div class="chart-wrap"><div class="chart-y"><span>${yen(max)}</span><span>${yen(max/2)}</span><span>¥0</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="日別売上推移"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#bf5b3f" stop-opacity=".28"/><stop offset="1" stop-color="#bf5b3f" stop-opacity="0"/></linearGradient></defs><path d="M 0,92 L ${pts} L 100,92 Z" fill="url(#area)"/><polyline points="${pts}" fill="none" stroke="#ad4c32" stroke-width="2.3" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round"/>${vals.map((v,i)=>`<circle cx="${x(i)}" cy="${92-v/max*78}" r="1.5" fill="#fff" stroke="#ad4c32" stroke-width="1" vector-effect="non-scaling-stroke"/>`).join('')}</svg><div class="chart-x">${data.map(e=>`<span>${+e.date.slice(8)}日</span>`).join('')}</div></div>`}

function render(){const data=entries.filter(e=>e.date.startsWith(month)).sort((a,b)=>a.date.localeCompare(b.date)), totals=calculateMonth(data), costRate=totals.sales?totals.costs/totals.sales*100:0, delivery=data.reduce((s,e)=>s+calculateDay(e).deliverySales,0), target=Math.min(totals.sales/10000,100), label=new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long'}).format(new Date(`${month}-01T00:00:00`));app.innerHTML=`
<aside><div class="brand"><div>${icon('coffee')}</div><span>CAFE REST<br><b>MOKA</b></span></div><nav><a class="active">${icon('chart')}ダッシュボード</a><a>${icon('calendar')}営業データ</a></nav><div class="aside-foot">${icon('store')}<span>カフェレスト モカ<small>経営管理システム</small></span></div></aside>
<main><header class="top"><div><span class="eyebrow">MANAGEMENT DASHBOARD</span><h1>月間ダッシュボード</h1><p>今日も一日、おつかれさまです。</p></div><button class="primary add" data-new>${icon('plus')}営業データを入力</button></header>
<section class="month-nav"><button data-move="-1">‹</button><strong>${label}</strong><button data-move="1">›</button></section>
<section class="stats">${stat('月間累計売上',yen(totals.sales),`${data.length}日分の営業データ`,'main-stat')}${stat('原価',yen(totals.costs),`原価率 ${pct(costRate)}`)}${stat('粗利益',yen(totals.grossProfit),`粗利率 ${pct(totals.sales?totals.grossProfit/totals.sales*100:0)}`,'profit')}${stat('デリバリー手数料',yen(totals.fees),`手数料率 ${pct(delivery?totals.fees/delivery*100:0)}`)}</section>
<section class="target"><div class="target-icon">${icon('wallet')}</div><div class="target-copy"><span>月商目標 <b>¥1,000,000</b></span><strong>あと ${yen(Math.max(1000000-totals.sales,0))}</strong><div class="progress"><i style="width:${target}%"></i></div></div><div class="rate"><strong>${pct(target)}</strong><span>達成率</span></div></section>
<section class="dashboard-grid"><article class="panel chart-panel"><header><div><span class="eyebrow">SALES TREND</span><h2>日別売上推移</h2></div><span class="legend"><i></i>総売上</span></header>${data.length?chart(data):'<div class="empty">この月のデータはまだありません</div>'}</article>
<article class="panel records"><header><div><span class="eyebrow">RECENT RECORDS</span><h2>営業データ</h2></div></header><div class="record-list">${data.length?data.slice().reverse().map(e=>{const d=calculateDay(e);return `<button data-edit="${e.date}"><span class="date-badge"><b>${+e.date.slice(8)}</b><small>日</small></span><span class="record-money"><small>総売上</small><b>${yen(d.sales)}</b></span><span class="record-profit"><small>粗利益</small><b>${yen(d.grossProfit)}</b></span>${icon('edit')}</button>`}).join(''):'<div class="empty">データを入力してください</div>'}</div></article></section></main>`
  app.querySelector('[data-new]').onclick=()=>openModal(emptyEntry());app.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{month=moveMonth(month,Number(b.dataset.move));render()});app.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal(entries.find(e=>e.date===b.dataset.edit)))
}
const money=(label,name,value)=>`<label class="money-input"><span>${label}</span><div><b>¥</b><input inputmode="numeric" name="${name}" value="${value||''}" placeholder="0"></div></label>`
function openModal(initial){const oldDate=initial.date, wrap=document.createElement('div');wrap.className='overlay';wrap.innerHTML=`<div class="modal"><header><div><span class="eyebrow">DAILY RECORD</span><h2>営業データを入力</h2></div><button class="icon-btn" data-close aria-label="閉じる">${icon('close')}</button></header><form><div class="modal-body"><label class="date-field">${icon('calendar')}<span>営業日</span><input name="date" type="date" value="${initial.date}" required></label>
${group('店内売上','rust',money('店内での売上','dineIn',initial.dineIn))}${group('デリバリー売上','gold',[['Uber Eats','uber'],['出前館','demae'],['Rocket Now','rocket']].map(([label,key])=>`<div class="delivery-row"><strong>${label}</strong>${money('注文売上',key+'Order',initial[key+'Order'])}${money('実入金',key+'Paid',initial[key+'Paid'])}</div>`).join(''))}${group('経費','green',`<div class="two-col">${money('食材仕入','ingredients',initial.ingredients)}${money('備品・消耗品','supplies',initial.supplies)}</div>`)}<div class="preview"><span>この日の総売上<strong data-sales>¥0</strong></span><span>粗利益<strong data-profit>¥0</strong></span></div></div><footer><button type="button" class="ghost" data-close>キャンセル</button><button class="primary">保存する</button></footer></form></div>`;document.body.append(wrap);const form=wrap.querySelector('form'),close=()=>wrap.remove(),update=()=>{const data=Object.fromEntries(new FormData(form));wrap.querySelector('[data-sales]').textContent=yen(calculateDay(data).sales);wrap.querySelector('[data-profit]').textContent=yen(calculateDay(data).grossProfit)};wrap.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);wrap.onclick=e=>{if(e.target===wrap)close()};form.querySelectorAll('input').forEach(i=>{i.oninput=()=>{if(i.type!=='date')i.value=i.value.replace(/\D/g,'');update()}});form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));numberFields.forEach(k=>data[k]=Number(data[k])||0);entries=entries.filter(x=>x.date!==oldDate&&x.date!==data.date).concat(data).sort((a,b)=>a.date.localeCompare(b.date));localStorage.setItem('moka-entries-v1',JSON.stringify(entries));month=data.date.slice(0,7);close();render()};update();form.querySelector('input').focus()}
const group=(title,color,content)=>`<section class="input-group"><h3><span class="dot ${color}"></span>${title}</h3>${content}</section>`
render()
